Import("Kronos_Env")

s_Kronos_Env = Kronos_Env.Clone()

Kronos_Env["CPPPATH"] = [
    "../Dep/glad/include",
    "../Dep/GLFW/include",
    "../Dep/imgui",
    "../Dep/Assimp/include",
    "../Header"]

Source = [Glob("*.cpp")]

SourceObj = Kronos_Env.Object(Source)

Return("SourceObj")